name: 77nn.it
url: https://77nn.it
description: TiTiNoNero dice cose
# uncomment to add announcement
announcement: "Blog su social, scienza, tecnologia, etica e privacy. Buona lettura!"

sass:
  style: compressed
  sourcemap: development
# possible values: nested expanded compact compressed
